backend/urls.py
from django.urls import path
from backend import views
from backend import api_views


app_name = "backend"


urlpatterns = [
    # Static pages
    path("test/", views.hello),
    path("sign_in/", views.sign_in, name="sign_in"),
    path("sign_out/", views.sign_out, name="sign_out"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("index/", views.index, name="index"),
    path("table_display/", views.table_disp, name="table_display"),
    path("dataCollection/", views.dataCollection, name="dataCollection"),
    path(
        "createCustomTable/", views.createCustomTable, name="createCustomTable"
    ),
    path("analytics/", views.analytics, name="analytics"),
    path("analytics/<int:customTableId>", views.analytics, name="analytics"),
    # visualisation
    path("visualisation/", views.visualisation, name="visualisation"),
    path(
        "visualisation/<int:customTableId>",
        views.visualisation,
        name="visualisation",
    ),
    # API endpoints
    path("api/sign_up", api_views.sign_up),
    path("api/sign_in", api_views.sign_in),
    path("api/create_campaign", api_views.create_campaign),
    path("api/create_custom_table", api_views.create_custom_table),
    path("api/analytics", api_views.analytics),
    path("api/forecast/", api_views.forecast),
    path("api/export/<int:customTableId>", api_views.export_csv),
]

finalProject/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("backend.urls")),
    path("stub/", include("stubapi.urls")),
    # stub/facebook/api/
    # stub/facebook/post - create new post form
    # stub/facebook/ - facebook home
    # stub/twitter/api
]

backend/models.py
from django.contrib.auth.models import User
from django.db import models
from jsonfield import JSONField
import pandas as pd


class CustomTable(models.Model):
    """
    id
    tableName
    tableStructure
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    structure = JSONField()

    def get_df(self):
        campaign1, campaign2 = self.structure
        fields1, fields2 = self.structure[campaign1], self.structure[campaign2]

        df1_fields_map = {}
        df2_fields_map = {}

        for fIdx in range(len(fields1)):
            if fields1[fIdx] != fields2[fIdx]:
                # perform type casting
                df1_fields_map[
                    fields1[fIdx]
                ] = f"{fields1[fIdx]}__{fields2[fIdx]}"
                df2_fields_map[
                    fields2[fIdx]
                ] = f"{fields1[fIdx]}__{fields2[fIdx]}"
            else:
                df1_fields_map[fields1[fIdx]] = fields1[fIdx]
                df2_fields_map[fields2[fIdx]] = fields2[fIdx]

        df1 = Data.objects.filter(campaign__id=campaign1).order_by(
            "-created_at"
        )[0]
        df1 = pd.DataFrame(df1.data)
        df1["Campaign Name"] = Campaign.objects.get(id=campaign1).name
        df2 = Data.objects.filter(campaign__id=campaign2).order_by(
            "-created_at"
        )[0]
        df2 = pd.DataFrame(df2.data)
        df2["Campaign Name"] = Campaign.objects.get(id=campaign2).name

        # output table
        finalDf = pd.concat(
            [
                df1.rename(columns=df1_fields_map),
                df2.rename(columns=df2_fields_map),
            ],
            ignore_index=True,
        )

        return finalDf

    def get_json(self):
        return self.get_df().to_json()


class Campaign(models.Model):
    """ 
    id
    customTable
    startDate
    crawlInterval
    lastUpdate (timestamp)
    """

    DAILY = 1440
    WEEKLY = 10080
    MONTHLY = 43800
    # interval in minutes
    CRAWL_INTERVAL_OPTIONS = (
        (DAILY, "daily"),
        (WEEKLY, "weekly"),
        (MONTHLY, "monthly"),
    )

    SOURCE_TYPE_OPTIONS = (
        ("csv", "CSV"),
        ("api", "API"),
        ("sm", "Social Media")
        # ("ct", "CustomTable"), # Maybe do this later - dont need this level of complexity now
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    sourceType = models.CharField(
        max_length=5, choices=SOURCE_TYPE_OPTIONS, default="api"
    )
    # Source can be different depending upon sourceType
    # fileName - csv
    # apiID - api
    # socialMedia - sm
    source = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    crawlInterval = models.IntegerField(choices=CRAWL_INTERVAL_OPTIONS)
    fields = JSONField()


class Data(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    data = JSONField()

backend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from backend.models import Campaign, CustomTable
import json
from plotly.offline import plot
from plotly.graph_objs import Scatter
import plotly.graph_objects as go


def hello(request):
    return render(request, "backend/index.html")


def sign_in(request):
    return render(request, "backend/sign_in.html")


@login_required(login_url="/sign_in")
def index(request):
    user = request.user
    campaigns = Campaign.objects.filter(user=user)
    customTables = CustomTable.objects.filter(user=user)
    return render(
        request,
        "backend/dashboard.html",
        {"user": user, "campaigns": campaigns, "customTables": customTables},
    )


@login_required(login_url="/sign_in")
def dataCollection(request):
    user = request.user
    return render(request, "backend/dataCollection.html", {"user": user})


@login_required(login_url="/sign_in")
def createCustomTable(request):
    user = request.user
    campaigns = Campaign.objects.filter(user=user)
    return render(
        request,
        "backend/createCustomTable.html",
        {"user": user, "campaigns": campaigns},
    )


@login_required(login_url="/sign_in")
def analytics(request, customTableId=None):
    user = request.user
    if customTableId is None:
        customTables = CustomTable.objects.filter(user=user)
        response = render(
            request, "backend/analytics.html", {"customTables": customTables}
        )
    else:
        response = render(
            request, "backend/analytics.html", {"customTableId": customTableId}
        )
    return response


def sign_out(request):

    logout(request)
    return redirect("/sign_in")


def sign_up(request):

    return render(request, "backend/sign_up.html")


def table_disp(request):

    return render(request, "backend/table_disp.html")


def visualisation(request, customTableId=None):

    user = request.user
    if customTableId is None:
        customTables = CustomTable.objects.filter(user=user)
        response = render(
            request,
            "backend/visualisation.html",
            {"customTables": customTables},
        )
    else:
        customTable = CustomTable.objects.get(id=customTableId)
        data = json.loads(customTable.get_json())

        response = render(
            request,
            "backend/visualisation.html",
            {"customTableId": customTableId},
        )
    return response

backend/templates/backend/analytics.html
{% extends 'backend/base.html' %} {% block content %}
<!-- sidebar -->
{% include 'backend/sidebar.html' %}
<div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">
        {% include 'backend/topbar.html' %}
        <div class="container-fluid">
            <h2>Analytics</h2>
            {% if customTables %}
            <div class="row">
                <div class="container-fluid">
                    <h3>Select a Table</h3>
                    <br />
                    {% for table in customTables %}
                    <a href="{% url 'backend:analytics' table.id %}">
                        <div class="col col-4 mt-2">
                            <div class="card bg-primary text-white shadow">
                                <div class="card-body">
                                    {{ table.name }}
                                    <!-- <div class="text-white-50 small">
                                            {{ campaign.created_at }}
                                        </div> -->
                                </div>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
            {% else %}
            <div class="row">
                <div class="col">
                    <form class="form-inline">
                        <label class="my-1 mr-2">Function</label>
                        <select class="custom-select my-1 mr-sm-2"
                            id="selectFunction">
                            <option value="sum">Sum</option>
                            <option value="mean">Mean</option>
                            <option value="median">Median</option>
                            <option value="min">Min</option>
                            <option value="max">Max</option>
                            <option value="T">Transpose</option>
                            <option value="groupby">Group By</option>
                            <option value="pivot">Pivot</option>
                        </select>

                        <label class="my-1 mr-2">Column</label>
                        <select id="selectColumn"
                            class="custom-select my-1 mr-sm-2">
                        </select>

                        <button id="applyFunction" type="button"
                            class="btn btn-primary my-1">
                            Apply
                        </button>
                        <div class="col">
                            <div id="functionResult"
                                style="color: black; font-weight: bold; font-size: 1.2rem;">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <h2>Forecasting</h2>
            <form class="form-inline forecast">
                <label class="my-1 mr-2">column1</label>
                <select
                    class="custom-select my-1 mr-sm-2 forecasting-select-column"
                    id="selectFunction">
                </select>

                <label class="my-1 mr-2">column2</label>
                <select id="selectColumn"
                    class="custom-select my-1 mr-sm-2 forecasting-select-column">
                </select>

                <input type="text"
                    class="form-control form-control-user my-1 mr-sm-2"
                    name="column1-value" placeholder="Enter value of column1" />

                <button id="forecastFunction" type="button"
                    class="btn btn-primary my-1">
                    Forecast
                </button>
                <div class="col">
                    <div id="forecastingResult" class="mt-2"
                        style="color: black; font-weight: bold; font-size: 1.2rem;">
                    </div>
                </div>
            </form>
            <div class="row">
                <input type="hidden" id="customTableId"
                    value="{{ customTableId }}" />
                <div
                    style="display: block; position: absolute; height: 65%; width: 85%; overflow: scroll;">
                    <table class="table table-bordered dataTable" id="dataTable"
                        cellspacing="0" role="grid" style="background: white;">
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        if ($('#customTableId').val()) {
            loadTable(customTableId);
        }

        $('#applyFunction').click(function () {
            applyFunction(
                $('#customTableId').val(),
                $('#selectFunction').val(),
                $('#selectColumn').val()
            );
        });
        $('#forecastFunction').click(function () {
            forecastFunction(
                $('#customTableId').val(),
                $('.forecasting-select-column:eq(0)').val(),
                $('.forecasting-select-column:eq(1)').val(),
                $('.forecast input').val()
            );
        });
    });

    function loadTable(customTableId) {
        $.post(
            '/api/analytics',
            { data: JSON.stringify({ customTableId: $('#customTableId').val(), functions: {} }) },
            function (response) {
                var table = response.table;
                var data = $.parseJSON(table.data);
                createTable(data);
            }
        );
    }

    function applyFunction(customTableId, fn, column) {
        var data = {
            customTableId: customTableId,
            functions: {}
        };
        data.functions[fn] = column;
        $.post('/api/analytics', { data: JSON.stringify(data) }, function (
            response
        ) {
            if (response.table) {
                console.log(response.table);
                $('#dataTable').empty();
                createTable($.parseJSON(response.table.data));
            } else {
                $('#functionResult').html(response.result);
            }
        });
    }

    function createTable(data) {
        $('#dataTable').append(
            "<thead><tr id='header' role='row'></tr></thead><tbody id='tableBody'></tbody>"
        );
        // populate columns
        var columns = Object.keys(data);
        columns.forEach(function (column) {
            $('#header').append(`<th>${column}</th>`);
            $('#selectColumn').append(
                `<option value="${column}">${column}</option>`
            );
            $('.forecasting-select-column:eq(0)').append(
                `<option value="${column}">${column}</option>`
            );
            $('.forecasting-select-column:eq(1)').append(
                `<option value="${column}">${column}</option>`
            );
        });

        // populate rows
        var rowIds = Object.keys(data[columns[0]]);
        rowIds.forEach(function (row) {
            var rowData = '<tr>';
            columns.forEach(function (col) {
                rowData += `<td>${data[col][row]}</td>`;
            });
            rowData += '</tr>';
            $('#tableBody').append(rowData);
        });
    }
    function forecastFunction(customTableId, column1, column2, column1_x) {
        let data = {
            customTableId: customTableId,
            column1: column1,
            column2: column2,
            column1_x: column1_x
        };
        $.post('/api/forecast/', { data: JSON.stringify(data) }, function (
            response
        ) {
            console.log(response);
            if (response !== undefined) {
                $('#forecastingResult').html(
                    `${column2}: ${response.predictedVal}`
                );
            }
        });
    }
</script>
{% endblock %}

backend/templates/backend/base.html
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Social Media Analytics</title>

    <!-- Custom fonts for this template-->
    <link href="/static/vendor/fontawesome-free/css/all.css" rel="stylesheet"
        type="text/css" />
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet" />

    <!-- Custom styles for this template-->
    <link href="/static/css/sb-admin-2.css" rel="stylesheet" />

    <!-- Bootstrap core JavaScript-->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- jspdf for exporting html as pdf-->
    <script src="https://unpkg.com/jspdf@latest/dist/jspdf.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
    <script type="text/javascript"
        src="https://html2canvas.hertzen.com/dist/html2canvas.js"></script>
</head>

<body>
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Content Wrapper -->
        {% block content %} {% endblock%}
        <!-- End of Content Wrapper -->

        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">
                            Ready to Leave?
                        </h5>
                        <button class="close" type="button" data-dismiss="modal"
                            aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Select "Logout" below if you are ready to end your
                        current session.
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button"
                            data-dismiss="modal">
                            Cancel
                        </button>
                        <a class="btn btn-primary"
                            href="{% url 'backend:sign_out' %}">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<!-- Custom scripts for all pages-->
<script src="/static/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="/static/vendor/chart.js/Chart.min.js"></script>

<!-- Page level custom scripts -->
<script src="/static/js/demo/chart-area-demo.js"></script>
<script src="/static/js/demo/chart-pie-demo.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        // Code for data collection page
        selectMap = {
            sm: '#selectSocialMedia',
            api: '#selectAPI',
            csv: '#selectCSV'
        };
        // Default
        $('#optionalElements div').hide();
        $(selectMap[$('#sourceType').val()]).show();

        $('#sourceType').on('change', function () {
            $('#optionalElements div').hide();
            $(selectMap[$(this).val()]).show();
        });

        // Code for mapping page
        $('#campaign1Fields > div').hide();
        $(`#campaign1Fields #${$('#campaign1').val()}`).show();
        $('#campaign1').on('change', function () {
            $('#campaign1Fields > div').hide();
            $(`#campaign1Fields #${$('#campaign1').val()}`).show();
        });
        $('#campaign2Fields > div').hide();
        $(`#campaign2Fields #${$('#campaign2').val()}`).show();
        $('#campaign2').on('change', function () {
            $('#campaign2Fields > div').hide();
            $(`#campaign2Fields #${$('#campaign2').val()}`).show();
        });

        $('#create-mapping').click(function () {
            var data = {};
            data[$('#campaign1').val()] = [];
            data[$('#campaign2').val()] = [];
            for (
                var i = 0;
                i <
                $(`#campaign1Fields #${$('#campaign1').val()} div div`)
                    .length;
                i++
            ) {
                let checked = $(
                    `#campaign1Fields #${$(
                        '#campaign1'
                    ).val()} div div:eq(${i}) input`
                )[0].checked;
                if (checked) {
                    let key = $.trim(
                        $(
                            `#campaign1Fields #${$(
                                '#campaign1'
                            ).val()} div div:eq(${i})`
                        ).text()
                    );
                    let val = $(
                        `#campaign2Fields #${$(
                            '#campaign2'
                        ).val()} select:eq(${i})`
                    ).val();
                    data[$('#campaign1').val()].push(key);
                    data[$('#campaign2').val()].push(val);
                    console.log(key);
                }
            }
            data['name'] = $('#customTableName').val();
            console.log(data);

            if (data['name'] === "") {
                alert('Enter Custom Table Name');
                return;
            }
            $.post(
                '/api/create_custom_table',
                { data: JSON.stringify(data) },
                function (response) {
                    console.log(response);
                    location.href = "/index";
                }
            );
        });
    });
</script>

</html>

backend/templates/backend/createCustomTable.html
{% extends 'backend/base.html' %} {% block content %}
<!-- sidebar -->
{% include 'backend/sidebar.html' %}
<div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">
        {% include 'backend/topbar.html' %}
        <div class="container-fluid">
            <h2>Cross Platform Mapping</h2>
            <br>
            <input type="text" id="customTableName"
                placeholder="Custom Table Name"><br><br>
            <div class="row">
                <div class="col col-md-4 text-center"
                    style="background-color: #fa7b62; color: black;">
                    <h3 class="mt-2">Campaign 1</h3>
                    <form>
                        <div class="form-group">
                            <label>Select Campaign</label>
                            <select id="campaign1" class="form-control"
                                name="campaign1">
                                {% for campaign in campaigns %}
                                <option value="{{ campaign.id }}">
                                    {{ campaign.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div id="campaign1Fields" class="form-group text-right">
                            {% for campaign in campaigns %}
                            <div id="{{ campaign.id }}">
                                {% for field in campaign.fields %}
                                <div class="row">
                                    <div class="col mt-2"
                                        style="height: calc(1.5em + 0.75rem + 2px); padding: 0.375rem 0.75rem;">
                                        <input class="form-check-input"
                                            type="checkbox" checked>
                                        {{ field }}
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="col col-md-4 text-center"
                    style="background-color: #ffff9f; color: black;">
                    <h3 class="mt-2">Campaign 2</h3>
                    <form>
                        <div class="form-group">
                            <label>Select Campaign</label>
                            <select id="campaign2" class="form-control"
                                name="campaign2">
                                {% for campaign in campaigns %}
                                <option value="{{ campaign.id }}">
                                    {{ campaign.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div id="campaign2Fields" class="form-group text-right">
                            {% for campaign in campaigns %}
                            <div id="{{ campaign.id }}">
                                {% for field in campaign.fields %}
                                <select name="{{ campaign.id }}"
                                    id="{{ campaign.id }}"
                                    class="form-control mt-2">
                                    {% for field in campaign.fields %}
                                    <option value="{{ field }}">{{ field }}
                                    </option>
                                    {% endfor %}
                                </select>
                                {% endfor %}
                            </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="col col-md-4 text-center">
                    <h3 class="mt-2"></h3>
                </div>
            </div>

            <button id="create-mapping" class="btn btn-primary mt-5">
                Create Mapping
            </button>
        </div>
    </div>
</div>
{% endblock %}

backend/templates/backend/dataCollection.html
{% extends 'backend/base.html' %} {% block content %}
<!-- sidebar -->
{% include 'backend/sidebar.html' %}
<div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">
        <!-- topbar here -->
        {% include 'backend/topbar.html' %}

        <br />
        <!-- Add Campaign-->
        <div class="row">
            <div class="col-md-6 offset-md-2">
                <h2>Create Campaign</h2>
                <form id="fromCreateCampaign" class="user container"
                    action="/api/create_campaign" method="POST"
                    enctype="multipart/form-data">
                    <div class="form-group">
                        <input type="text" name="campaignName"
                            class="form-control form-control-user"
                            placeholder="Campaign Name" />
                    </div>
                    <div class="form-group">
                        <label>Data Source</label>
                        <select id="sourceType" class="form-control"
                            name="sourceType">
                            <!-- <option value="sm">Social Media</option> -->
                            <option value="api">API Endpoint</option>
                            <option value="csv">CSV File</option>
                        </select>
                    </div>
                    <div id="optionalElements">
                        <div id="selectSocialMedia" class="form-group">
                            <label>Select Social Media</label>
                            <select id="socialMedia" class="form-control"
                                name="socialMedia">
                                <option value="facebook">Facebook</option>
                                <option value="twitter">Twitter</option>
                                <option value="google">Google</option>
                            </select>
                        </div>
                        <div id="selectAPI" class="form-group">
                            <input type="text"
                                class="form-control form-control-user"
                                name="api" placeholder="Enter API Endpoint" />
                        </div>
                        <div id="selectCSV" class="form-group">
                            <input id="fileupload" type="file" name="file"
                                multiple>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="text"
                            class="form-control form-control-user" name="fields"
                            placeholder="Fields" />
                    </div>
                    <div class="form-group">
                        <label>Schedule</label>
                        <div class="row">
                            <div class="checkbox col-md-2">
                                <label><input type="radio" name="schedule"
                                        value="DAILY" />
                                    Daily</label>
                            </div>
                            <div class="checkbox col-md-2">
                                <label><input type="radio" name="schedule"
                                        value="WEEKLY" />
                                    Weekly</label>
                            </div>
                            <div class="checkbox col-md-2">
                                <label><input type="radio" name="schedule"
                                        value="MOTHLY" />
                                    Monthly</label>
                            </div>
                        </div>
                    </div>
                    <input type="submit"
                        class="btn btn-primary btn-user btn-block"
                        value="Add Social Media" />
                </form>
            </div>
        </div>
    </div>
    <!-- End of Main Content -->
</div>

{% endblock %}